sudo: false
language: ruby
rvm:
- 2.0
- 2.1
- 2.2
matrix:
  include:
    - rvm: 1.9.3
      env: BUNTO_VERSION=1.0
env:
  matrix:
    - BUNTO_VERSION=1.0
    - BUNTO_VERSION=2.0
branches:
  only:
    - master
before_script:
  - chmod a+x script/bootstrap
  - chmod a+x script/cibuild
  - chmod a+x script/release
script: script/cibuild
notifications:
  irc:
    on_success: change
    on_failure: change
    channels:
    - irc.freenode.org#bunto
    template:
    - '%{repository}#%{build_number} %{message} %{build_url}'
  email:
    on_success: never
    on_failure: change
