# Travis CI
sudo: false
language: ruby
rvm:
- 2.3.1
- 2.3.0
- ruby-head
matrix:
  allow_failures:
    - rvm: ruby-head
  include:
    - rvm: 2.2.5
      env: BUNTO_VERSION=3.0.0
env:
  matrix:
    - BUNTO_VERSION=3.2.1
    - BUNTO_VERSION=3.0.0
branches:
  only:
    - master
before_script:
  - chmod a+x script/bootstrap
  - chmod a+x script/cibuild
  - chmod a+x script/release
install:
- travis_retry script/bootstrap
script: script/cibuild
notifications:
  irc:
    on_success: never
    on_failure: never
  email:
    on_success: never
    on_failure: never
